# Generated by Django 4.2.8 on 2023-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_pracy', models.FloatField(max_length=10)),
                ('woda', models.FloatField(max_length=10)),
                ('posilki', models.IntegerField(max_length=10)),
                ('cwiczenia', models.BooleanField()),
                ('przerwy_ilosc', models.IntegerField(max_length=10)),
                ('przerwy_czas', models.IntegerField(max_length=10)),
            ],
        ),
    ]
