# Generated by Django 4.2.8 on 2023-12-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='nazwa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='czas_pracy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='posilki',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='przerwy_czas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='przerwy_ilosc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='woda',
            field=models.FloatField(),
        ),
    ]
